<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_ProgressBar
 */

use Jhonathan\ProgressBar\Block\Frontend\Progress;

/**
 * @var $block Progress
 */
?>

<?php $data = $block->execute(); ?>

<div class="js-content-progress">
    <div class="js-progress-bar-percent" style="width: <?= $data['percent']; ?>%;">&nbsp;</div>
    <div class="js-progress-bar-text" style=""><?= $data['text']; ?></div>
</div>
