<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_ProgressBar
 */

use Jhonathan\ProgressBar\Block\Frontend\Progress;

/**
 * @var $block Progress
 */
?>

<?php $data = $block->execute(); ?>

<div class="js-content-progress" style="background-color: <?= $data['colors']['color1']?>; border: 1px solid <?= $data['colors']['color1']?>;">
    <div class="js-progress-bar-percent" style="background-color: <?= $data['colors']['color2']?>; width: <?= $data['percent']; ?>%;">&nbsp;</div>
    <div class="js-progress-bar-text" style="color: <?= $data['colors']['text']?>;"><?= $data['text']; ?></div>
</div>
