<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_Whatsapp
 */

use Jhonathan\Whatsapp\Block\Frontend\Whatsapp;

/**
 * @var $block Whatsapp
 */
?>

<?php $several = $block->hasSeveralNumbers(); ?>

<?php if($several): ?>
    <?=
        $block->addChild('whatsapp.theme.multiple', Whatsapp::class, [
            'multiple' => $several,
            'template' => 'Jhonathan_Whatsapp::theme/multiple.phtml'
        ])->toHtml();
    ?>
<?php else: ?>
    <?=
        $block->addChild('whatsapp.theme.simple', Whatsapp::class, [
            'simple' => $several,
            'template' => 'Jhonathan_Whatsapp::theme/simple.phtml'
        ])->toHtml();
    ?>
<?php endif; ?>
