<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_Vortex
 */

use Jhonathan\Customer\Block\Widget\Taxvat;
use Magento\Customer\Helper\Address;
use Magento\Framework\Escaper;

/**
 * @var Taxvat $block
 * @var Escaper $escaper
 */
?>

<div class="js field taxvat<?= $block->isRequired() ? ' required' : ''; ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')); ?>">
        <span>
            <?= $escaper->escapeHtml($block->getStoreLabel('taxvat')); ?>
        </span>
    </label>
    <div class="control">
        <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')); ?>" name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()); ?>" title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')); ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('taxvat')); ?>" <?= $block->isRequired() ? ' data-validate="{required:true}"' : '' ?>>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "js_init": {
                "element": {
                    "0": "<?= "input#" . $escaper->escapeHtmlAttr($block->getFieldId('taxvat')); ?>"
                },
                "mask": {
                    "0": "<?= $escaper->escapeJs($block->getMask()); ?>"
                },
                "validate": {
                    "0": "true"
                }
            }
        }
    }
</script>