<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_Vortex
 */

use Jhonathan\Customer\Block\Widget\Zip;
use Magento\Framework\Escaper;

/**
 * @var Zip $block
 * @var Escaper $escaper
 */
?>

<div class="field zip required">
    <label for="zip" class="label">
        <span>
            <?= $escaper->escapeHtml($block->getStoreLabel('postcode')); ?>
        </span>
    </label>
    <div class="control">
        <input type="text" name="postcode" value="<?= $escaper->escapeHtmlAttr($block->getPostcode()); ?>" title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')); ?>" id="zip" class="input-text validate-zip-international <?= $escaper->escapeHtmlAttr($block->getValidationClass()); ?>">
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "js_init": {
                "element": {
                    "0": "<?= "input#" . $escaper->escapeHtmlAttr($block->getFieldId('zip')); ?>"
                },
                "mask": {
                    "0": "00000-000"
                },
                "validate": {
                    "0": "true"
                }
            }
        }
    }
</script>