<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_Whatsapp
 */

use Jhonathan\Whatsapp\Block\Frontend\Whatsapp;

/**
 * @var $block Whatsapp
 */
?>

<?php $simple = $block->getData('simple'); ?>

<div class="js-whatsapp-simple" <?= $block->getPosition(); ?>>
    <a href="<?= $block->formatUrlWhatsapp(55, $block->getNumberPhone($simple)); ?>" target="_blank">
        <img src="<?= $block->getImgWhatsapp(); ?>" alt="whatsapp" />
    </a>
</div>
